dungeon:
  worldName: "letopis_dungeon"
  lobby:
    x: 0
    y: 80
    z: 0
    yaw: 0
    pitch: 0
  rules:
    denyBlockBreak: true
    denyBlockPlace: true
    denyExplosions: true
  run:
    maxMinutes: 35
  director:
    baseTensionPerMinute: 20
    successDrop: 60
  structure:
    placeCommandTemplate: "place structure %key% %x% %y% %z%"
    baseY: 70

ui:
  bossbar:
    enabled: true
