# Задаёт языковой файл, используемый EliteMobs.
# Не меняйте это вручную! Язык должен устанавливаться командой '/em language <languagefile>'.
language: english
# Определяет, будут ли элиты и боссы EliteMobs всегда показывать свои именные теги.
# Не рекомендуется!
alwaysShowEliteMobNameTags: false
# Задаёт количество пассивных мобов, которые должны быть рядом для объединения.
# Не устанавливайте 0!
superMobStackAmount: 50
# Запрещает элитам наносить урон пассивным мобам взрывами.
preventEliteCreeperDamageToPassiveMobs: true
# Определяет, будут ли EliteMobs использовать титры для предупреждений о нехватке прав.
useTitlesForMissingPermissionMessages: true
# Определяет, будут ли EliteMobs запрещать превращение именованных мобов в элит.
# Особенно важно для совместимости с другими плагинами.
preventEliteMobConversionOfNamedMobs: true
# Определяет, будут ли EliteMobs превращать мобов с кастомной причиной спавна.
# Запуск некоторых плагинов боссов автоматически установит это в true, независимо от значения в конфиге.
enableHighCompatibilityMode: false
# Задаёт бонус к спавну элит для режима Nightmare.
nightmareWorldSpawnBonus: 0.5
# Определяет, открывает ли команда /em основную страницу статуса плагина.
# Настоятельно рекомендуется!
emLeadsToStatusMenu: true
# Определяет, ведут ли команды вроде /em wallet в меню /em, где эта информация централизована.
otherCommandsLeadToEMStatusMenu: true
# Определяет, завершена ли настройка.
# Не устанавливайте это значение вручную, оно должно меняться через игровые команды.
setupDoneV4: false
# Определяет, будут ли элиты предотвращать спавн ванильных подкреплений (например, у зомби).
preventVanillaReinforcementsForEliteEntities: true
# Задаёт точку спавна сервера для EliteMobs. /em spawntp перенесёт в эту точку.
defaultSpawnLocation: world,0.0,109.0,0.0,0.0,0.0
# Определяет, будут ли EliteMobs восстанавливать блоки, взорванные элитами.
doExplosionRegen: true
# Определяет, будет ли восстановление взрывов также восстанавливать содержимое контейнеров (например, сундуков).
# Если отключить, взрывы элит не будут разрушать контейнеры.
doRegenerateContainers: true
defaultTransitiveBlockLimiter: 500
# Определяет, будет ли меню /em использовать только инвентарный стиль, совместимый с Bedrock.
# Напоминание: игроки могут использовать /em alt для переключения стилей меню /em.
onlyUseBedrockMenus: false
# Задаёт лимит символов на строку для меню-книг.
# Уменьшите, если текст обрезается в меню-книгах (например, квестов).
characterLimitForBookMenuPagesV2: 170
# Определяет, заполняются ли пустые ячейки меню стеклянными панелями.
# Не рекомендуется при использовании ресурс-пака EliteMobs.
useGlassToFillMenuEmptySpace: false
# Задаёт сообщение при использовании /em confirm без ожидающих команд.
noPendingCommands: '&cСейчас нет ожидающих команд!'
# Задаёт сообщение отслеживания для боссов, отправляющих сообщения отслеживания.
trackMessage: Отслеживание: $name
# Задаёт сообщение для игроков, открывающих сундуки с требованием уровня выше их ранга гильдии.
chestLowRankMessage: '&7[EM] &cВаш ранг гильдии должен быть не ниже $rank, чтобы открыть
  этот сундук!'
# Задаёт сообщение для игроков, пытающихся повторно открыть уже открытый сундук.
chestCooldownMessage: '&7[EM] &cВы уже недавно открывали этот сундук! Подождите $time!'
# Задаёт сообщение с рекомендацией /em alt для игроков с проблемами команды /em.
dismissEMMessage: '&8[EliteMobs] &2/elitemobs &fменю не работает? Попробуйте &2/elitemobs
  alt &fдля альтернативной версии меню! &cНе хотите видеть это сообщение снова?
  &4/em dismiss'
# Задаёт сообщение при использовании команды /em alt.
switchEMStyleMessage: '&8[EliteMobs] &2/elitemobs &fстиль меню изменён! Посмотрите!'
# Задаёт сообщение, когда игрок открывает сундук и ничего не получает.
treasureChestNoDropMessage: '&8[EliteMobs] &cВы ничего не получили! Повезёт в следующий
  раз!'
# Задаёт сообщение при попытке отследить босса, который больше недоступен.
bossAlreadyGoneMessage: '&c[EliteMobs] Извините, этого босса уже нет!'
# Определяет, сбрасывать ли масштаб игрока (размер персонажа при входе).
# Это важно, потому что некоторые силы элит меняют масштаб, и при краше сервера игроки застрянут с тем масштабом, который был выставлен, если не включить этот параметр.
resetPlayerScale: true
# Задаёт сообщение при провале испытания зачарования.
enchantmentChallengeFailureMessage: '&8[EliteMobs] &cЗачарование не удалось! Чары
  не привязались к предмету.'
# Задаёт сообщение при успешном испытании зачарования.
enchantmentChallengeSuccessMessage: '&8[EliteMobs] &2Успешное зачарование!'
# Задаёт сообщение, если во время испытания зачарования инвентарь заполнен.
enchantmentChallengeInventoryFullMessage: '&8[EliteMobs] &cВаш инвентарь был заполнен,
  поэтому предмет для улучшения удалён! Он восстановится, если к моменту выхода из
  инстанс‑подземелья инвентарь будет не заполнен.'
# Задаёт сообщение о последствиях испытания зачарования.
enchantmentChallengeConsequencesMessage: '&cЕсть 10% шанс потерять предмет при поражении!
  Выход из арены считается поражением.'
# Задаёт сообщение при критическом провале испытания зачарования.
enchantmentChallengeCriticalFailureMessage: '&8[EliteMobs] &4Критическая неудача!
  Вы потеряли предмет!'
# Задаёт сообщение в начале испытания зачарования.
enchantmentChallengeStartMessage: '&8[EliteMobs] &6Испытание! Победите босса, чтобы
  получить улучшенный предмет!'
# Разрешает использование ресурс-паков, даже если менеджер ресурс-паков не установлен.
useResourcePackEvenIfResourcePackManagerIsNotInstalled: false
# Определяет, будет ли масштаб (размер) элит слегка рандомизирован для разнообразия.
# Может влиять на спавнеры, что может быть как плюсом, так и минусом (я считаю, что плюс >:]).
useRandomizedScalingForElites: true
