# Определяет, включена ли экономика EliteMobs. Это включает в себя элитные монеты, возможность покупать и продавать снаряжение, а также повышать ранги гильдии.
# Если отключено, игроки не смогут прогрессировать в плагине!
enableEconomy: true
# Задаёт стоимость перепродажи предметов в % от исходной цены. 5 = 5%.
itemResaleValue: 5.0
# Задаёт внутриигровое название используемой валюты.
currencyName: Элитные монеты
# Задаёт использование Vault. НЕ РЕКОМЕНДУЕТСЯ! Подробнее: https://github.com/MagmaGuy/EliteMobs/wiki/%5BThird-party-support%5D-Vault
useVault - not recommended: false
# Определяет, будут ли элиты ронять монеты в зависимости от их уровня.
enableCurrencyShower: true
# Задаёт множитель валюты, выпадающей с элит.
currencyShowerTierMultiplier: 1.0
# Задаёт сообщение, отправляемое при поднятии элитной валюты.
chatCurrencyShowerMessage: '&7[EM] Вы подняли &a$amount $currency_name!'
# Задаёт экшен-бар сообщение при поднятии элитной валюты.
actionbarCurrencyShowerMessage: '&7[EM] Вы подняли &a$amount $currency_name!'
lootShowerDataV2:
  '1': elitemobs:coins/coin1
  '5': elitemobs:coins/coin1
  '10': elitemobs:coins/coin2
  '20': elitemobs:coins/coin3
  '50': elitemobs:coins/coin4
  '100': elitemobs:coins/coin4
  '500': elitemobs:coins/coin4
  '1000': elitemobs:coins/coin4
# Отправляет сообщение игрокам после поднятия валюты. Полезно для обучения.
adventurersGuildNotificationMessages: '&7[EM] Хотите подзаработать? Попробуйте &a/ag !'
# Задаёт налоговую ставку для транзакций между игроками.
# Настоятельно рекомендуется для баланса: игроки высокого уровня могут получать до 6x больше валюты и пытаться обходить сбросы престижа через других игроков.
playerToPlayerPaymentTaxes: 0.2
# Сообщение, отправляемое при переводе элитной валюты другим игрокам.
Economy pay message v2: '&2Вы отправили &2$amount_sent $currency_name &2игроку $receiver&2,
  он получил $amount_received после налогов!'
# Сообщение, отправляемое после отправки валюты.
Economy currency left message: Теперь у вас &2$amount_left $currency_name
# Сообщение, получаемое при получении валюты.
Economy money from payment message: Вы получили &2$amount_received $currency_name
  &fот $sender
# Сообщение при попытке отправить больше монет, чем есть.
Economy payment insufficient currency: '&cУ вас недостаточно $currency_name для этого!'
# Сообщение команды /em balance.
Wallet command message: У вас &2$balance $currency_name
# Подтверждение, отправляемое при попытке перевода валюты другому игроку.
Tax confirmation message: '&cОтправка платежа стоит $percentage% налога. &aВведите
  &9$command &aдля подтверждения!'
# Сообщение при покупке в магазине.
Shop buy message: '&aВы купили $item_name &aза $item_value $currency_name!'
# Сообщение при взаимодействии с магазином.
Shop current balance message: '&aУ вас $currency_amount $currency_name.'
# Сообщение, когда игроку не хватает валюты для покупки предмета.
Shop insufficient funds message: '&cУ вас недостаточно $currency_name!'
# Вторая часть сообщения при попытке купить предмет, который игрок не может себе позволить.
Shop item cost message: Этот предмет стоит &c$item_value $currency_name.
# Сообщение при продаже предмета магазину.
Shop sell message: '&aВы продали $item_name &aза $currency_amount $currency_name!'
# Сообщение при попытке продать предмет, который не принадлежит игроку.
Shop sale player items warning: '&cНельзя продавать предметы, которые не привязаны
  к вам! Это включает предметы других уровней престижа!'
# Сообщение при попытке продать предмет не из EliteMobs.
Shop sale instructions: '&cЗдесь можно продавать только лут EliteMobs! (Броня / оружие
  от элитных мобов с ценой в описании)'
# Сообщение при продаже партии элитных предметов.
shopBatchSellItem: '&aВы продали свои предметы &aза $currency_amount $currency_name!'
lootShowerMaterial:
  # Задаёт тип материала для 1 выпавшей элитной монеты.
  '1': GOLD_NUGGET
  '5': GOLD_INGOT
  '10': GOLD_BLOCK
  '20': EMERALD
  '50': EMERALD_BLOCK
  '100': DIAMOND
  '500': DIAMOND_BLOCK
  '1000': NETHER_STAR
lootShowerData:
  # Задаёт ID пользовательской модели для 1 выпавшей элитной монеты (используется ресурс-паком).
  '1': 1
materialWorth:
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  DIAMOND_AXE: 17.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  DIAMOND_BOOTS: 17.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  DIAMOND_CHESTPLATE: 17.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  DIAMOND_LEGGINGS: 17.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  DIAMOND_HELMET: 17.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  DIAMOND_PICKAXE: 17.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  DIAMOND_SHOVEL: 17.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  DIAMOND_SWORD: 17.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  DIAMOND_HOE: 17.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  IRON_AXE: 16.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  IRON_BOOTS: 16.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  IRON_LEGGINGS: 16.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  IRON_CHESTPLATE: 16.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  IRON_HELMET: 16.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  IRON_PICKAXE: 16.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  IRON_SHOVEL: 16.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  IRON_HOE: 16.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  IRON_SWORD: 16.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  SHIELD: 16.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  BOW: 16.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  CHAINMAIL_BOOTS: 15.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  CHAINMAIL_LEGGINGS: 15.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  CHAINMAIL_CHESTPLATE: 15.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  CHAINMAIL_HELMET: 15.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  STONE_SWORD: 15.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  STONE_AXE: 15.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  STONE_PICKAXE: 15.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  STONE_SHOVEL: 15.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  STONE_HOE: 15.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  GOLDEN_AXE: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  GOLDEN_BOOTS: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  GOLDEN_LEGGINGS: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  GOLDEN_CHESTPLATE: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  GOLDEN_HELMET: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  GOLDEN_SWORD: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  GOLDEN_SHOVEL: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  GOLDEN_PICKAXE: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  GOLDEN_HOE: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  GOLDEN_APPLE: 17.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  ENCHANTED_GOLDEN_APPLE: 17.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  LEATHER_BOOTS: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  LEATHER_LEGGINGS: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  LEATHER_CHESTPLATE: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  LEATHER_HELMET: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  WOODEN_SWORD: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  WOODEN_AXE: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  WOODEN_HOE: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  WOODEN_PICKAXE: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  TRIDENT: 17.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  ELYTRA: 17.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  TURTLE_HELMET: 13.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  NETHERITE_AXE: 18.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  NETHERITE_PICKAXE: 18.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  NETHERITE_SHOVEL: 18.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  NETHERITE_HOE: 18.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  NETHERITE_SWORD: 18.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  NETHERITE_HELMET: 18.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  NETHERITE_CHESTPLATE: 18.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  NETHERITE_LEGGINGS: 18.0
  # Задаёт ценность этого материала для валютной системы EliteMobs.
  NETHERITE_BOOTS: 18.0
  # Задаёт базовую ценность материала для предметов без явного определения.
  defaultMaterialWorth: 1.0
